### ISSUE TITLE
Confidence estimate for phased state between two adjacent site within a HaplotypeBlock?

### ISSUE THREAD

**Issue by everestial** [secastel/phaser#30] opened 2017-06-20 13:03 UTC
Hi @secastel 

As, I understand that PC is a confidence estimate for GW phase. But, I am interested in checking how good are adjacent alleles phased within `Haplotype Block, PI`. In the given data below is there a way to estimate confidence level for

    1860    1|0         vs.         1860    1|0 
    1879    0|1                     1879    1|0

    2	1860	.	T	G	22718.54	PASS	AC=6;AF=0.231;AN=26;BaseQRankSum=0.548;ClippingRankSum=0.00;DP=2218;ExcessHet=6.2249;FS=5.236;InbreedingCoeff=-0.3001;MQ=47.32;MQRankSum=0.00;QD=20.43;ReadPosRankSum=-5.100e-02;SOR=0.399;set=Intersection	GT:AD:DP:GQ:PL:PG:PB:PI:PW:PC	0/1:204,329:533:99:10442,0,7734:1|0:.,.,.,.,.:1036:|:0.5
    2	1879	.	G	A	11022.23	PASS	AC=8;AF=0.286;AN=28;BaseQRankSum=-4.150e-01;ClippingRankSum=0.00;DP=2210;ExcessHet=0.0577;FS=5.183;InbreedingCoeff=0.6497;MQ=60.00;MQRankSum=0.00;QD=10.93;ReadPosRankSum=0.049;SOR=1.060;set=Intersection	GT:AD:DP:GQ:PL:PG:PB:PI:PW:PC	0/1:326,208:534:99:5861,0,13140:0|1:.,.,.,.,.:1036:|:0.5

Is the confidence values (PC which is actually for GW PC)  good to estimate the confidence of PG at haplotype block level? My thought is no, because almost all my sites have PC as 0.5, since I didn't supply any phased vcf (which I don't have). Any other way I can estimate this?

Thanks,

**Comment by secastel** [comment] 2017-06-20 18:27
If you did not provide a phased VCF as input, then there is no information available to phASER that would allow it to estimate any sort of phase confidence between phase blocks. phASER only makes use of reads for estimating phasing. If there are no reads spanning phase blocks, and you did not use a phased VCF there is no way that it can determine phasing between haplotype blocks.

**Comment by everestial** [comment] 2017-06-20 22:53
@secastel 
I am talking about the alleles phased iwthin a haplotype block, not between blocks.

**Comment by everestial** [comment] 2017-06-20 22:55
Another issue:

I had this complaint:

    ##### ERROR MESSAGE: Key PG found in VariantContext field FORMAT at 2:422 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.

I check and no PG are in my output vcf. Used the updated version of phaser.

Thanks,

**Comment by secastel** [comment] 2017-06-21 19:22
Sorry, I misunderstood. There isn't a measure of phase confidence within blocks that you can find in the outputted VCF. This is actually done for each variant-variant pair that reads overlap. You can find the output of variant-variant phase confidence in the file "XXX.variant_connections.txt". As described in our paper, we have a statistical test the compares the read based phase support for two variants to the noise level seen in the sample. A significant (default: nominal p < 0.01) "conflicting_configuration_p" indicates that conflicting phase information is higher than what is expected by noise alone, and these variant-variant connections are then dropped when assembling haplotype blocks.

From the paper: "During the first step the phase with the most supporting reads is chosen, and a binomial test is performed to determine if the number of reads supporting alternative phases is greater than would be expected from sequencing noise, allowing for filtering of low confidence phasing (Supplementary Figs. 1a, 2a)".

About the second issue, I am unable to reproduce this using the current version of phASER. Is it only the PG tag that is missing, or all of the phASER tags (PG, PB, PI, PM, PW, PC)?

**Comment by everestial** [comment] 2017-06-21 21:08
Hi @secastel 
Thanks for details on 'phase confidence within block'.

Yeah, it's only `PG` tag that is missing. And, it is missing from all different samples. I tried to `force merge` them because I have to do another level of data analyses, no tool is able to proceed with having the `HEADER` info correct. Absence of `PG` in header wouldn't matter much for what I am doing, but even after adding `PG` for each vcf manually, I cannot get them to merge.
Not, sure if it's leading to other formatting problems.

**Comment by secastel** [comment] 2017-06-21 21:16
Hmm, very odd. I just tried "bcftools merge" with two phASER outputted VCFs, and they went together no problem. Can you try gunzip -c XX.vcf.gz | grep "##FORMAT=<" for one of the VCFs and posting the result here? I'd like to see all tags that got added to the outputted file.

**Comment by everestial** [comment] 2017-06-22 16:47
Hi
The PG tag are indeed missing. I am not sure why? I am just replicated the problem on a small data.
[passed_variants.All_samples_test.vcf.gz](https://github.com/secastel/phaser/files/1095538/passed_variant
[2ms02g_Only_Chr2.vcf.gz](https://github.com/secastel/phaser/files/1095540/2ms02g_Only_Chr2.vcf.gz)
s.All_samples_test.vcf.gz)
[2ms01e_Only_Chr2.vcf.gz](https://github.com/secastel/phaser/files/1095539/2ms01e_Only_Chr2.vcf.gz)

**Comment by secastel** [comment] 2017-06-26 17:05
Thanks for uploading these files. I believe I have identified the problem and it should be fixed in the latest version of phASER v0.9.9.5. Please give it a try and let me know, and thanks again for bringing up the issue!

**Closed** 2019-11-03 07:23 UTC
